name: 'Build Container Image'
description: 'Build a container image using Docker Buildx'
inputs:
  context:
    description: 'The build context'
    required: true
    default: '.'
  dockerfile:
    description: 'Path to the Dockerfile'
    required: true
    default: './Dockerfile'
  push:
    description: 'Push the built image'
    required: false
    default: 'false'
  tags:
    description: 'Tags for the Docker image'
    required: false
    default: ''
  github-token:
    description: 'GitHub Token'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build Container image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
