name: build-push-image

on:
  workflow_call:
    inputs:
      tags:
        description: 'Tags to push the Docker image with'
        required: true
        type: string
    secrets:
        github-token:
          description: 'GitHub Token'
          required: true

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.github-token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.tags }}